name: train-pipeline

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]
    # optionally use a convenient Ubuntu LTS + CUDA + DVC + CML image
    container: docker://dvcorg/cml-py3:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Train Model
        env: 
          repo_token: $(( secrets.GITHUB_TOKEN ))
        run: |
         echo 'Install dependencies...'
         pip3 install -r requirements.txt
         echo 'Train Model...'
         python3 train.py
         echo 'Training complete!'

      - name: Write CML Report
        env: 
          repo_token: $(( secrets.GITHUB_TOKEN ))
        run: |      
         echo '## Model Metrics' >> report.md
         cat model/metrics.txt >> report.md

         echo '## Performance Plots' >> report.md
         cml-publish model/confusion_matrix.png --md >> report.md
         cml-publish model/feature_importance.png --md >> report.md
         
         cml-send-comment report.md
