name: train-pipeline

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]
    # optionally use a convenient Ubuntu LTS + CUDA + DVC + CML image
    # container: docker://continuumio/anaconda3
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
  
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2

      - name: Train model
        run: |
          conda activate test
          conda install scikit-learn
          python train.py

      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Post reports as comments in GitHub PRs
          echo "MODEL METRICS"
          cat metrics.txt >> report.md
          cml-send-comment report.md
